server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # --- Account Service ---
        - id: accountservice
          uri: lb://accountservice
          predicates:
            - Path=/accounts/**
          filters:
            - StripPrefix=0

        # --- Account Service Swagger (access via gateway) ---
        - id: accountservice-docs
          uri: lb://accountservice
          predicates:
            - Path=/accountservice/v3/api-docs/**
          filters:
            - RewritePath=/accountservice/(?<segment>.*), /${segment}

        # --- Customer Service (future) ---
        #- id: customerservice
        #  uri: lb://customerservice
        #  predicates:
        #    - Path=/customers/**

        # --- Transaction Service (future) ---
        #- id: transactionservice
        #  uri: lb://transactionservice
        #  predicates:
        #    - Path=/transactions/**

  # --- Keycloak OAuth2 (Gateway as Resource Server) ---
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/banking-realm
          jwk-set-uri: http://localhost:8080/realms/banking-realm/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: "*"


